2. Разметка главной страницы
htmlacademy-htmlcss/944533-sedona-30 pull request #2
Opened 2021-01-24 16:46 UTC by KsenyBond

2021-01-25 06:30 UTC, craz3r requested changes

2021-01-25 06:30 UTC, craz3r commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru" method="get">
Мне кажется использовать форму в этой сортировке будет лишним, здесь это скорее ссылки, ведь нет кнопки сабмита формы, и по логике фильтрация будет происходить сразу после клика на элемент

2021-01-25 06:30 UTC, craz3r commented on catalog.html
> +            <img src="https://via.placeholder.com/135x90" width="135" height="90" alt="Отель Amara Resort & Spa">
Изображение гостиницы и ее название должны быть ссылками на внутреннюю страницу гостиницы

2021-01-26 06:08 UTC, craz3r requested changes

2021-01-26 06:08 UTC, craz3r commented on catalog.html
> +          </li>
Пропущена сортировка по возрастанию/убыванию (то что на макете изображено в виде стрелок)

2021-01-26 11:19 UTC, KsenyBond commented on catalog.html
> +          </li>
Добавила ссылки, а стрелки будут через background-image, как я понимаю

2021-01-27 06:16 UTC, craz3r approved these changes

2021-01-27 06:16 UTC, merged